### ISSUE TITLE
Install section in README

### ISSUE THREAD

**Issue by richiejp** [acerv/kirk#1]
It would be nice to have a generic install section in the README. Like a list of python packages or just run `setup.py` or a pointer to the CI setup if that contains the canonical way to install the deps for development.

**Comment by acerv** [comment]
Agree with that. I'm gonna add it now. For now, consider virtualenv the official way to install kirk:

```
# from python 3.6+
virtualenv .venv
source .venv/bin/activate
pip install .
```

**Comment by acerv** [comment]
https://github.com/acerv/kirk/tree/readme_install

**Comment by acerv** [comment]
Add `runkirk` script and fixed documentation to include install / dependences
