### ISSUE TITLE
Wrong kirk version

### ISSUE THREAD

**Issue by czerw** [acerv/kirk#4]
Latest kirk version is 1.1, but source still contains 1.1:
https://github.com/acerv/kirk/blob/21e2953e318caa8be0d2a427b1e29de733a1d7ef/libkirk/__init__.py#L16

**Comment by acerv** [comment]
Thanks for pointing out. It's fixed now:

https://github.com/acerv/kirk/commit/e55f96cc2bdc6e47941e34866cd79706fa0c63ce
https://github.com/acerv/kirk/releases/tag/v1.1
